### ISSUE TITLE
haven received tokens

### ISSUE THREAD

**Issue by dedogordo33** [YGEM-finance/swap#4]
hi, I ve made the transaction but I haven't received the tokens TXid 0x5647fd7ef6804600c8ab85c37988a8befbb92d719597f537c5a1270b54f69a8a
transaction wasn't going through so I tried to speed it up and it just showed failed transaction so I did it again, but both of them ended up going through.

**Comment by MindfulMe** [comment]
Hello, here is the alternative guide on how to swap without a website (works 100%): 
1) Go to https://etherscan.io/address/0xd63ee441da6cd37e30d2c351c66a0b7404d07316#readContract (you can skip this step if you already done the approve spend limit transaction on the website)
<img width="1249" alt="Screenshot 2020-10-27 at 10 32 11" src="https://user-images.githubusercontent.com/26275425/97276313-b0042500-183f-11eb-81a7-f435176b2c2a.png">
(press "query" to get the balance).

Copy your balance (in uint256). Note: This is the amount is in Wei, if you have 1 ygem you will have 1* 10^18 in Wei amount.

Then paste the swap contract address 0xf513a29715e82b215ad697ecdea4932e7631ec61 and the balance here https://etherscan.io/address/0xd63ee441da6cd37e30d2c351c66a0b7404d07316#writeContract
<img width="442" alt="Screenshot 2020-10-27 at 10 34 39" src="https://user-images.githubusercontent.com/26275425/97276555-07a29080-1840-11eb-85e1-b40050f4c08e.png">
Press "Write" and confim in Metamask.

2) Once you approve the spending limit of old YGEMs you have to go here https://etherscan.io/address/0xf513a29715e82b215ad697ecdea4932e7631ec61#writeContract

Connect your Metamask and paste the amount that you copied already from step 1 (in uint256) there. Do not forget to press the write button and confirm in Metamask,.

<img width="390" alt="Screenshot 2020-10-27 at 10 36 50" src="https://user-images.githubusercontent.com/26275425/97276786-54866700-1840-11eb-894e-2db7ecf15f47.png">

**Comment by dedogordo33** [comment]
Done, thank you!
